---
## Before attempting to create FS you must create a partition table on the new disk.
## You can use fdisk, cfisk, sfdisk..
- name: Create ext4 filesystem
  filesystem: fstype=ext4
              dev=/dev/sdb1
              opts="-cc"
              force=yes
  tags: filesystem

- name: Mount filesystem
  mount: name=/srv/sdb1
         src=/dev/sdb1
         fstype=ext4
         state=mounted
         opts="defaults"
  tags: filesystem

- name: Ensure brick directory exists
  file: path={{Â item }}
        state=directory
  with_items:
    - "{{ gluster.brick_dir }}"
    - "{{ gluster.mount_dir }}"
  tags: filesystem

- name: Copy gluster gluster repo
  copy: src=gluster.repo
        dest=/etc/yum.repos.d/
  tags: [deployment, gluterfs]

- name: Install GlusterFS
  yum: name={{ item }}
       state=present
       update_cache=yes
  with_items:
    - glusterfs
    - glusterfs-server
    - glusterfs-fuse
  tags: [deployment, glusterfs]

- name: Ensure Gluster is running
  service: name=glusterd
           state=started
           enabled=yes
  tags: [deployment, glusterfs]

- name: Check if Gluster volumes already exist
  shell: "gluster volume info"
  register: gluster_volume_info
  tags: glusterfs

- name: Connect peers
  command: gluster peer probe {{ item }}
  with_items:
    - "{{ [groups['gluster_slaves']][0] }}"
  when: "'Volume Name: {{ gluster.vol_name }}' not in gluster_volume_info.stdout"
  register: gluster_probe_result
  changed_when: "'already in peer list' not in gluster_probe_result.stdout"
  run_once: true
  tags: glusterfs

  # http://adamj.eu/tech/2014/10/02/merging-groups-and-hostvars-in-ansible-variables/
- name: Get hosts list by comma separated
  debug:
    msg: |
      {% set comma = joiner(",") %}
      {% for item in [groups['gluster_slaves']][0] -%}
        {{ comma() }}{{ item }}
      {%- endfor %}
  run_once: true
  register: cluster_nodes_result
  tags: glusterfs

- name: Set hosts list as fact
  set_fact: cluster_nodes="{{ cluster_nodes_result.msg }}"

- name: Create and start gluster volume
  gluster_volume: state=present
                  name="{{ gluster.vol_name }}"
                  replicas={{ item }}
                  brick="{{ gluster.brick_dir }}"
                  cluster="{{ cluster_nodes }}"
                  transport=tcp
                  force=true
  with_items:
    - "{{ [groups['gluster_slaves']][0] | length }}"
  when: "'Volume Name: {{ gluster.vol_name }}' not in gluster_volume_info.stdout"
  run_once: true
  ignore_errors: yes
  tags: glusterfs



